name: Deploy Backend Server to EC2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy Backend to EC2
      uses: appleboy/ssh-action@master
      with:
        host: '3.136.200.153'
        username: ec2-user
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Navigate to server directory and update code
          cd ~/server
          git pull origin main
          
          # Navigate to docker-compose directory
          cd ~/docker-compose
          
          # Rebuild and restart the backend container
          docker-compose -f dockercompose.yml stop backend-server
          docker-compose -f dockercompose.yml build backend
          docker-compose -f dockercompose.yml up -d backend
